USE ESCOLA
CREATE TABLE ALUNOS
(
	PK_ALUNO INT PRIMARY KEY,
	NOME VARCHAR (50),
	TIPO VARCHAR (50)
)

CREATE TABLE MATERIA
(
	PK_MATERIA INT PRIMARY KEY,
	MATERIA VARCHAR (50),
	DESCRICAO VARCHAR (50)
)

CREATE TABLE ALUNO_X_MATERIA
(
	FK_ALUNO INT,
    FK_MATERIA INT,
    PRIMARY KEY (FK_ALUNO, FK_MATERIA),
    CONSTRAINT FK_ALUNO FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS (PK_ALUNO),
    CONSTRAINT FK_MATERIA FOREIGN KEY (FK_MATERIA) REFERENCES MATERIA (PK_MATERIA)
)
