
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

SELECT [CODIGO DO PRODUTO] AS [CODIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'

INSERT INTO [PRODUTOS] ([CODIGO], [DESCRITOR], [SABOR], [TAMANHO], [EMBALAGEM], [PREÇO LISTA])
SELECT [CODIGO DO PRODUTO] AS [CODIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'